version: '3.8'

services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:16-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pg_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/:/tmp/data/      